Create README.md
On my ubuntu 16.04 I had to install libcap-dev otherwise I get the message : 
```Running python-prctl-1.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-akxp66iq/python-prctl-1.6.1/egg-dist-tmp-ckm7a3jz
You need to install libcap development headers to build this module
error: Setup script exited with 1
```